# .gitlab-ci.yml

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest

deploy:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - gunicorn -w 4 -b 0.0.0.0:8000 app:app
